<a href="https://colab.research.google.com/github/JohanAv1018/Proyecto-Final-Diplomado-Curso-II/blob/main/Proyecto_final_Diplomado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Sección 1. Introducción y pregunta de análisis**

---

###**Introducción**
El dataset utilizado en este proyecto es “Social Media vs Productivity”, publicado por Mahdi Mashayekhi en Kaggle.

**Fuente:**\
https://www.kaggle.com/datasets/mahdimashayekhi/social-media-vs-productivity


**Licencia:**\
CC BY-NC-SA 4.0

**Fecha de consulta:**\
05 de Mayo de 2026

Este dataset analiza la relación entre el uso de redes sociales y distintos indicadores de productividad, bienestar y hábitos laborales.
Contiene alrededor de 30.000 registros y algunas variables como:
tiempo diario en redes sociales.

*   Productividad percibida y real.
*   Niveles de estrés.
*   Horas de sueño.
*   Satisfacción laboral.
*   Promedio de horas trabajadas.
*   Etc.

---

### **Relevancia del problema**

En la actualidad, las redes sociales forman parte de la rutina diaria de millones de personas y consumen una cantidad significativa de tiempo durante actividades académicas y laborales. Debido a esto, ha surgido interés en comprender cómo el uso constante de estas plataformas puede influir en la productividad y el bienestar.

Analizar la relación entre hábitos digitales y variables como estrés, sueño, satisfacción laboral o desempeño permite identificar patrones de comportamiento y comprender mejor el impacto del uso de redes sociales en la vida cotidiana.

---

###**Pregunta de análisis**
- ¿Qué relación existe entre los hábitos digitales y los indicadores de productividad y bienestar?

---

#**Sección 2: Carga y exploración inicial**

---

###**Librerías**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

---
### **Carga del dataset**

El dataset se carga directamente desde el repositorio de GitHub mediante una URL RAW, permitiendo que el análisis sea completamente reproducible.

In [9]:
url_df = "https://raw.githubusercontent.com/JohanAv1018/Proyecto-Final-Diplomado-Curso-II/main/social_media_vs_productivity_df.csv"
df = pd.read_csv(url_df)

---
### **Exploración básica**

En esta sección se realiza una exploración inicial del dataset para conocer sus dimensiones, tipos de variables, valores únicos y estadísticas descriptivas.

In [11]:
#Dimensión del dataset
df.shape

(30000, 19)

Tenemos un total de 19 variables y 30.000 observaciones en este dataset.

---

In [16]:
#Información de las variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             30000 non-null  int64
 1   gender                          30000 non-null  object
 2   job_type                        30000 non-null  object
 3   daily_social_media_time         27235 non-null  float64
 4   social_platform_preference      30000 non-null  object
 5   number_of_notifications         30000 non-null  int64
 6   work_hours_per_day              30000 non-null  float64
 7   perceived_productivity_score    28386 non-null  float64
 8   actual_productivity_score       27635 non-null  float64
 9   stress_level                    28096 non-null  float64
 10  sleep_hours                     27402 non-null  float64
 11  screen_time_before_sleep        27789 non-null  float64
 12  breaks_during_work              30000 non-null  int64
 13  uses_focus_apps                 30000 non-null  bool
 14  has_digital_wellbeing_enabled   30000 non-null  bool
 15  coffee_consumption_per_day      30000 non-null  int64
 16  days_feeling_burnout_per_month  30000 non-null  int64
 17  weekly_offline_hours            30000 non-null  float64
 18  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(5), object(3)
memory usage: 3.9+ MB

Se identifican variables numéricas, categóricas y booleanas, ya que cada variable tiene la categoría adecuada, no es necesario realizar alguna corrección con respecto a esto.

---

In [17]:
# Cantidad de valores únicos por columna
df.nunique()

age                                  48
gender                                3
job_type                              6
daily_social_media_time           25375
social_platform_preference            5
number_of_notifications              61
work_hours_per_day                29821
perceived_productivity_score      28386
actual_productivity_score         27635
stress_level                         10
sleep_hours                       26926
screen_time_before_sleep          25567
breaks_during_work                   11
uses_focus_apps                       2
has_digital_wellbeing_enabled         2
coffee_consumption_per_day           11
days_feeling_burnout_per_month       32
weekly_offline_hours              26737
job_satisfaction_score            27079
dtype: int64

In [19]:
# Estadísticas descriptivas
df.describe()

,age,daily_social_media_time,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
count,30000.000000,27235.000000,30000.000000,30000.000000,28386.000000,27635.000000,28096.000000,27402.000000,27789.000000,30000.000000,30000.000000,30000.000000,30000.000000,27270.000000
mean,41.486867,3.113418,59.958767,6.990792,5.510488,4.951805,5.514059,6.500247,1.025568,4.992200,1.999300,15.557067,10.360655,4.964901
std,13.835221,2.074813,7.723772,1.997736,2.023470,1.883378,2.866344,1.464004,0.653355,3.173737,1.410047,9.252956,7.280415,2.121194
min,18.000000,0.000000,30.000000,0.000000,2.000252,0.296812,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,1.639566,55.000000,5.643771,3.757861,3.373284,3.000000,5.493536,0.528490,2.000000,1.000000,8.000000,4.541872,3.363580
50%,41.000000,3.025913,60.000000,6.990641,5.525005,4.951742,6.000000,6.498340,1.006159,5.000000,2.000000,16.000000,10.013677,4.951049
75%,53.000000,4.368917,65.000000,8.354725,7.265776,6.526342,8.000000,7.504143,1.477221,8.000000,3.000000,24.000000,15.300809,6.581323
max,65.000000,17.973256,90.000000,12.000000,8.999376,9.846258,10.000000,10.000000,3.000000,10.000000,10.000000,31.000000,40.964769,10.000000

---
### **Primeras observaciones**

A simple vista, el dataset contiene una gran cantidad de registros y variables relacionadas con hábitos digitales, productividad y bienestar. También se observa la presencia de variables numéricas y categóricas que permitirán realizar distintos tipos de análisis y visualizaciones.

Además, la exploración inicial permitirá identificar posibles valores faltantes, variables relevantes para el análisis y relaciones potenciales entre el uso de redes sociales y diferentes indicadores de desempeño y bienestar.

---

#**Sección 3. Limpieza y transformación.**
---

### **Verificación de valores faltantes**

Se identifican posibles valores nulos dentro del dataset para determinar si es necesario aplicar algún tratamiento de limpieza.

In [20]:
df.isnull().sum()

age                                  0
gender                               0
job_type                             0
daily_social_media_time           2765
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                      1904
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

Se identificó la presencia de valores faltantes en algunas variables numéricas del dataset, principalmente relacionadas con productividad, estrés, sueño y satisfacción laboral.

Debido a que estas variables son relevantes para el análisis y eliminar los registros implicaría una pérdida considerable de información, se decidió reemplazar los valores faltantes utilizando la mediana de cada variable numérica. Esta medida permite conservar la distribución de los datos y reduce el impacto de posibles valores extremos.

In [24]:
df = df.fillna(df.median(numeric_only=True))
df.isnull().sum()

age                               0
gender                            0
job_type                          0
daily_social_media_time           0
social_platform_preference        0
number_of_notifications           0
work_hours_per_day                0
perceived_productivity_score      0
actual_productivity_score         0
stress_level                      0
sleep_hours                       0
screen_time_before_sleep          0
breaks_during_work                0
uses_focus_apps                   0
has_digital_wellbeing_enabled     0
coffee_consumption_per_day        0
days_feeling_burnout_per_month    0
weekly_offline_hours              0
job_satisfaction_score            0
dtype: int64

---
### **Verificación de registros duplicados**

Se revisa si existen filas duplicadas que puedan afectar el análisis.

In [21]:
df.duplicated().sum()

np.int64(0)

Con lo anterior podemos notar que no existe filas duplicadas, por lo que en esta parte no será necesario aplicar ningún tratamiento ni modificación.